sonar.projectKey=spring-petclinic
sonar.projectName=Spring PetClinic
sonar.projectVersion=4.0.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.sourceEncoding=UTF-8
