# Production VM for the Vagrant path. On Apple Silicon use Multipass
# instead, see the README. Put the Jenkins public key next to this file
# as jenkins_key.pub before vagrant up.

JENKINS_PUBKEY = File.expand_path("jenkins_key.pub", __dir__)

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "petclinic-prod"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "petclinic-prod"
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end

  config.vm.provider "parallels" do |prl|
    prl.memory = 2048
    prl.cpus = 2
  end

  if File.exist?(JENKINS_PUBKEY)
    config.vm.provision "file", source: JENKINS_PUBKEY, destination: "/tmp/jenkins_key.pub"
    config.vm.provision "shell", inline: <<-SHELL
      install -d -m 700 -o vagrant -g vagrant /home/vagrant/.ssh
      touch /home/vagrant/.ssh/authorized_keys
      grep -q -f /tmp/jenkins_key.pub /home/vagrant/.ssh/authorized_keys || \
        cat /tmp/jenkins_key.pub >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys
      chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys
    SHELL
  else
    config.vm.post_up_message = "jenkins_key.pub not found, generate the deploy key and run vagrant provision"
  end
end
